/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author John Esteban
 */
public class Iniciar extends javax.swing.JFrame {

    /**
     * Creates new form Iniciar
     */
    public Iniciar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("assets/logo_asuServicio(1).png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Menu_Perfil = new javax.swing.JLabel();
        Menu_Categorias = new javax.swing.JLabel();
        Menu_Configuracion = new javax.swing.JLabel();
        Menu_CerrarSe = new javax.swing.JLabel();
        X_Cerrar = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jButton_mecanico = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setSize(new java.awt.Dimension(742, 551));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Menu.setBackground(new java.awt.Color(0, 0, 0));
        Label_Menu.setForeground(new java.awt.Color(255, 255, 255));
        Label_Menu.setText("Menu");
        Label_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Label_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Menu_Perfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Menu_Perfil.setText("Perfil");

        Menu_Categorias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Menu_Categorias.setText("Categorias");

        Menu_Configuracion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Menu_Configuracion.setText("Configuracion");

        Menu_CerrarSe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Menu_CerrarSe.setText("Cerrar Sesion");

        X_Cerrar.setText("X");
        X_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_CerrarMouseClicked(evt);
            }
        });

        jPanel1.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Menu_Configuracion)
                            .addComponent(Menu_CerrarSe, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Menu_Categorias))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Menu_Perfil)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X_Cerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(X_Cerrar)
                .addGap(69, 69, 69)
                .addComponent(Menu_Perfil)
                .addGap(18, 18, 18)
                .addComponent(Menu_Categorias)
                .addGap(18, 18, 18)
                .addComponent(Menu_Configuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(Menu_CerrarSe)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jButton_salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jButton_mecanico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_mecanico.setText("MECANICOS");
        jButton_mecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mecanicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagen_fondo_5.jpeg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_mecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mecanicoActionPerformed
        Mecanicos_view verMecanicos_view = new Mecanicos_view();
        verMecanicos_view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_mecanicoActionPerformed

    private void Label_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label_MenuActionPerformed
        jPanel1.setVisible(true);
        Label_Menu.setVisible(false);
    }//GEN-LAST:event_Label_MenuActionPerformed

    private void X_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_CerrarMouseClicked
        jPanel1.setVisible(false);
        Label_Menu.setVisible(true);
    }//GEN-LAST:event_X_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Label_Menu;
    private javax.swing.JLabel Menu_Categorias;
    private javax.swing.JLabel Menu_CerrarSe;
    private javax.swing.JLabel Menu_Configuracion;
    private javax.swing.JLabel Menu_Perfil;
    private javax.swing.JLabel X_Cerrar;
    private javax.swing.JButton jButton_mecanico;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
