/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author eliro
 */
public class Mecanicos_view extends javax.swing.JFrame {

    /**
     * Creates new form Mecanicos_view
     */
    public Mecanicos_view() {
        initComponents();
        this.setLocationRelativeTo(null);
        //jLabel1.putClientProperty("JComponent.roundRect", true);
        UIManager.put( "jLabel.arc", 999 );
        
    }
    
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("assets/logo_asuServicio(1).png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        jButton_Menu = new javax.swing.JButton();
        jPanel_Menu = new javax.swing.JPanel();
        jButton_cerrar_panel = new javax.swing.JButton();
        jButton_Perfil = new javax.swing.JButton();
        jButton_Cerrar_sesion = new javax.swing.JButton();
        jButton_Categorias = new javax.swing.JButton();
        jButton_Configuracion = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setSize(new java.awt.Dimension(744, 551));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/4.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jButton_salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jButton_volver.setBackground(new java.awt.Color(0, 0, 0));
        jButton_volver.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jButton_Menu.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Menu.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_Menu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Menu.setText("Menu");
        jButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel_Menu.setBackground(new java.awt.Color(1, 72, 127));
        jPanel_Menu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_MenuComponentHidden(evt);
            }
        });

        jButton_cerrar_panel.setBackground(new java.awt.Color(0, 0, 0));
        jButton_cerrar_panel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_cerrar_panel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar_panel.setText("X");
        jButton_cerrar_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrar_panelActionPerformed(evt);
            }
        });

        jButton_Perfil.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Perfil.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Perfil.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Perfil.setText("Perfil");

        jButton_Cerrar_sesion.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Cerrar_sesion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cerrar_sesion.setText("Cerrar sesion");
        jButton_Cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cerrar_sesionActionPerformed(evt);
            }
        });

        jButton_Categorias.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Categorias.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Categorias.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Categorias.setText("Categorias");
        jButton_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CategoriasActionPerformed(evt);
            }
        });

        jButton_Configuracion.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Configuracion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Configuracion.setText("Configuracion");

        jPanel_Menu.setVisible(false);

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cerrar_panel)
                .addContainerGap())
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_Cerrar_sesion))
                    .addGroup(jPanel_MenuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Configuracion)
                            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton_Categorias)))))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_Perfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_cerrar_panel)
                .addGap(54, 54, 54)
                .addComponent(jButton_Perfil)
                .addGap(18, 18, 18)
                .addComponent(jButton_Categorias)
                .addGap(18, 18, 18)
                .addComponent(jButton_Configuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jButton_Cerrar_sesion)
                .addContainerGap())
        );

        getContentPane().add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagen_fondo_5.jpeg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        Iniciar verIniciar = new Iniciar();
        verIniciar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_cerrar_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_panelActionPerformed
        jPanel_Menu.setVisible(false);
        jButton_Menu.setVisible(true);
    }//GEN-LAST:event_jButton_cerrar_panelActionPerformed

    private void jButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MenuActionPerformed
        jPanel_Menu.setVisible(true);
        jButton_Menu.setVisible(false);
    }//GEN-LAST:event_jButton_MenuActionPerformed

    private void jButton_Cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cerrar_sesionActionPerformed
        JOptionPane.showMessageDialog(this, "Sesion cerrada con exito");
        login verlogin = new login();
        verlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Cerrar_sesionActionPerformed

    private void jButton_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CategoriasActionPerformed
        Iniciar verIniciar = new Iniciar();
        verIniciar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_CategoriasActionPerformed

    private void jPanel_MenuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_MenuComponentHidden

    }//GEN-LAST:event_jPanel_MenuComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mecanicos_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mecanicos_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mecanicos_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mecanicos_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mecanicos_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Categorias;
    private javax.swing.JButton jButton_Cerrar_sesion;
    private javax.swing.JButton jButton_Configuracion;
    private javax.swing.JButton jButton_Menu;
    private javax.swing.JButton jButton_Perfil;
    private javax.swing.JButton jButton_cerrar_panel;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JPanel jPanel_Menu;
    // End of variables declaration//GEN-END:variables
}
