/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;


import database.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author prestamo
 */
public class Perfil extends javax.swing.JFrame {
    private Connection con = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private String userName, password, email, userFullName;

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    public void dataPerfil() throws SQLException {
        
        try {
            // peticion del id
            login id = new login();
            int getId = id.getId();
            
            //nos conectamos a la base de datos
            con = Conexion.getInstancia().conectar();
            
            
            //consultamos a la base de datos los datos que queremos verificar
            String setQuery = "SELECT * FROM user_db WHERE id_user = ?";
            ps = con.prepareStatement(setQuery);
            ps.setInt(1, getId);
            
            rs = ps.executeQuery();
            
            if (rs.next()) {
                userName = rs.getString("user_name");
                password = rs.getString("user_password");
                email = rs.getString("user_email");
                userFullName = rs.getString("user_full_name");

                jLabel_nameuser_data.setText(userName);
                jLabel_password_data.setText(password);
                jLabel_email_data.setText(email);
                jLabel_fullname_data.setText(userFullName);
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontraron datos del perfil.");
            }
            
            //si hay resultados significa que los datos son correctos
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos del perfil: " + e.getMessage());
        } finally {
            // Cerramos los recursos
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (con != null) con.close();
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_foto_perfil = new javax.swing.JLabel();
        jLabel_nameuser_data = new javax.swing.JLabel();
        jLabel_password_data = new javax.swing.JLabel();
        jLabel_fullname_data = new javax.swing.JLabel();
        jLabel_email_data = new javax.swing.JLabel();
        jLabel_nameuser = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_fullname = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jButton_Menu = new javax.swing.JButton();
        jPanel_Menu = new javax.swing.JPanel();
        jButton_cerrar_panel = new javax.swing.JButton();
        jButton_Cerrar_sesion = new javax.swing.JButton();
        jButton_Categorias = new javax.swing.JButton();
        jButton_Configuracion = new javax.swing.JButton();
        jButton_volver = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_foto_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user_logo.png"))); // NOI18N
        getContentPane().add(jLabel_foto_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel_nameuser_data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel_nameuser_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel_password_data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel_password_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jLabel_fullname_data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel_fullname_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel_email_data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel_email_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jLabel_nameuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_nameuser.setText("nombre de usuario:");
        getContentPane().add(jLabel_nameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_password.setText("contraseña:");
        getContentPane().add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_email.setText("email:");
        getContentPane().add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel_fullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_fullname.setText("full name:");
        getContentPane().add(jLabel_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jButton_salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jButton_Menu.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Menu.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_Menu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Menu.setText("Menu");
        jButton_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel_Menu.setBackground(new java.awt.Color(1, 72, 127));
        jPanel_Menu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_MenuComponentHidden(evt);
            }
        });
        jPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Menu.setVisible(false);

        jButton_cerrar_panel.setBackground(new java.awt.Color(0, 0, 0));
        jButton_cerrar_panel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_cerrar_panel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar_panel.setText("X");
        jButton_cerrar_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrar_panelActionPerformed(evt);
            }
        });
        jPanel_Menu.add(jButton_cerrar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 6, -1, -1));

        jButton_Cerrar_sesion.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Cerrar_sesion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cerrar_sesion.setText("Cerrar sesion");
        jButton_Cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cerrar_sesionActionPerformed(evt);
            }
        });
        jPanel_Menu.add(jButton_Cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jButton_Categorias.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Categorias.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Categorias.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Categorias.setText("Categorias");
        jButton_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CategoriasActionPerformed(evt);
            }
        });
        jPanel_Menu.add(jButton_Categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton_Configuracion.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Configuracion.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Configuracion.setText("Configuracion");
        jButton_Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfiguracionActionPerformed(evt);
            }
        });
        jPanel_Menu.add(jButton_Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jButton_volver.setBackground(new java.awt.Color(0, 0, 0));
        jButton_volver.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        jPanel_Menu.add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        getContentPane().add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 550));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagen_fondo_5.jpeg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MenuActionPerformed
        jPanel_Menu.setVisible(true);
        jButton_Menu.setVisible(false);
    }//GEN-LAST:event_jButton_MenuActionPerformed

    private void jButton_cerrar_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrar_panelActionPerformed
        jPanel_Menu.setVisible(false);
        jButton_Menu.setVisible(true);
    }//GEN-LAST:event_jButton_cerrar_panelActionPerformed

    private void jButton_Cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cerrar_sesionActionPerformed
        JOptionPane.showMessageDialog(this, "Sesion cerrada con exito");
        login verlogin = new login();
        verlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Cerrar_sesionActionPerformed

    private void jPanel_MenuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_MenuComponentHidden

    }//GEN-LAST:event_jPanel_MenuComponentHidden

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        Categoria verCategoria = new Categoria();
        verCategoria.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CategoriasActionPerformed
        Categoria verCategoria = new Categoria();
        verCategoria.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_CategoriasActionPerformed

    private void jButton_ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfiguracionActionPerformed
        Configuracion verConfiguracion = new Configuracion();
        verConfiguracion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Perfil perfil = new Perfil();
                perfil.setVisible(true);
                try {
                    perfil.dataPerfil(); // Mueve esta llamada dentro de try-catch.
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(perfil, "Error al cargar datos: " + e.getMessage());
                    System.out.print("Error al cargar datos: " + e.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Categorias;
    private javax.swing.JButton jButton_Cerrar_sesion;
    private javax.swing.JButton jButton_Configuracion;
    private javax.swing.JButton jButton_Menu;
    private javax.swing.JButton jButton_cerrar_panel;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_email_data;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_foto_perfil;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_fullname_data;
    private javax.swing.JLabel jLabel_nameuser;
    private javax.swing.JLabel jLabel_nameuser_data;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_password_data;
    private javax.swing.JPanel jPanel_Menu;
    // End of variables declaration//GEN-END:variables
}
