/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author loaiz
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("assets/logo_asuServicio(1).png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        jLabel_user_logo = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_volver = new javax.swing.JButton();
        jLabel_password1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel_user1 = new javax.swing.JLabel();
        jTextField_user1 = new javax.swing.JTextField();
        jLabel_user2 = new javax.swing.JLabel();
        jTextField_user2 = new javax.swing.JTextField();
        jTextField_user3 = new javax.swing.JTextField();
        jLabel_user3 = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jLabel_registrarse = new javax.swing.JLabel();
        FonReg = new javax.swing.JLabel();
        jButton_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(742, 551));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_asuServicio(1).png"))); // NOI18N
        jLabel_logo.setToolTipText("");
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel_user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user_logo.png"))); // NOI18N
        getContentPane().add(jLabel_user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel_user.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setText("Usuario");
        getContentPane().add(jLabel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jTextField_user.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_userActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, 20));

        jLabel_password.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Repita contraseña");
        getContentPane().add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jPasswordField.setBackground(new java.awt.Color(190, 221, 255));
        jPasswordField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 140, 20));

        jButton_volver.setBackground(new java.awt.Color(0, 0, 0));
        jButton_volver.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jLabel_password1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_password1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password1.setText("Contraseña");
        getContentPane().add(jLabel_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(190, 221, 255));
        jPasswordField1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 140, 20));

        jLabel_user1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user1.setText("Correo electronico");
        getContentPane().add(jLabel_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jTextField_user1.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 20));

        jLabel_user2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user2.setText("Numero de celular");
        getContentPane().add(jLabel_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jTextField_user2.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 140, 20));

        jTextField_user3.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, 20));

        jLabel_user3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user3.setText("Nombre completo");
        getContentPane().add(jLabel_user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jButton_salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register (1).png"))); // NOI18N
        getContentPane().add(jLabel_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        FonReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagen_fondo_5.jpeg"))); // NOI18N
        getContentPane().add(FonReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton_registrar.setText("jButton1");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_userActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        login verlogin = new login();
        verlogin.setVisible(true);
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jTextField_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user1ActionPerformed

    private void jTextField_user2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user2ActionPerformed

    private void jTextField_user3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user3ActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        Iniciar verIniciar=new Iniciar();
        verIniciar.setVisible(true);
    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FonReg;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_password1;
    private javax.swing.JLabel jLabel_registrarse;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JLabel jLabel_user1;
    private javax.swing.JLabel jLabel_user2;
    private javax.swing.JLabel jLabel_user3;
    private javax.swing.JLabel jLabel_user_logo;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_user;
    private javax.swing.JTextField jTextField_user1;
    private javax.swing.JTextField jTextField_user2;
    private javax.swing.JTextField jTextField_user3;
    // End of variables declaration//GEN-END:variables
}
