/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import database.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author loaiz
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("assets/logo_asuServicio(1).png"));
        return retValue;
    }
    
    //metodo para insertar los datos de los usuarios que se registren 
    private void registrarUsuario() {
        //obtenemos los valores de los campos de texto
        String nombre = jTextField_user_name.getText();
        String email = jTextField_user_email.getText();
        String pNumber = jTextField_user_pNumber.getText();
        String username = jTextField_user.getText();
        String password = new String(jPasswordField1.getPassword());
        String confirmPassword = new String(jPasswordField.getPassword());
        
        //verificar si las contraseñas coinciden
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coninciden");
            return;
        }
        
        //verificamos que no haya campos vacios
        if (nombre.isEmpty() || email.isEmpty() || pNumber.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
            return;
        }
        
        //nos conectamos a la base de datos
        Conexion conexion = Conexion.getInstancia();
        Connection conr = conexion.conectar();
        
        //preparamos la sentencia para insertar datos en la base de datos
        String sql = "INSERT INTO user_db (user_full_name, user_email, user_pNumber, user_name, user_password) VALUES (?, ?, ?, ?, ?)";
    
        try (PreparedStatement psr = conr.prepareStatement(sql)) {
            // Establecemos los parámetros en la consulta
            psr.setString(1, nombre);
            psr.setString(2, email);
            psr.setString(3, pNumber);
            psr.setString(4, username);
            psr.setString(5, password);
            
            //ejecutamos la consulta
            int rowsAffected = psr.executeUpdate();
            
            //condiciones para verificar si se logro registrar el nuevo usuario
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Nuevo usuario, registrado con exito");
                login verlogin = new login();
                verlogin.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el nuevo usuario");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de la base de datos: " + e.getMessage());
        } finally {
            //desconectar de la base de datos
            conexion.desconectar();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        jLabel_user_logo = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_volver = new javax.swing.JButton();
        jLabel_password1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel_user_email = new javax.swing.JLabel();
        jTextField_user_email = new javax.swing.JTextField();
        jLabel_user_pNumber = new javax.swing.JLabel();
        jTextField_user_pNumber = new javax.swing.JTextField();
        jTextField_user_name = new javax.swing.JTextField();
        jLabel_user_name = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jLabel_registrarse = new javax.swing.JLabel();
        FonReg = new javax.swing.JLabel();
        jButton_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_asuServicio(1).png"))); // NOI18N
        jLabel_logo.setToolTipText("");
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel_user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user_logo.png"))); // NOI18N
        getContentPane().add(jLabel_user_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel_user.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setText("Usuario");
        getContentPane().add(jLabel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jTextField_user.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_userActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 170, 20));

        jLabel_password.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Repita contraseña");
        getContentPane().add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jPasswordField.setBackground(new java.awt.Color(190, 221, 255));
        jPasswordField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 170, 20));

        jButton_volver.setBackground(new java.awt.Color(0, 0, 0));
        jButton_volver.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jLabel_password1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_password1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password1.setText("Contraseña");
        getContentPane().add(jLabel_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(190, 221, 255));
        jPasswordField1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 170, 20));

        jLabel_user_email.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user_email.setText("Correo electronico");
        getContentPane().add(jLabel_user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jTextField_user_email.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user_email.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, 20));

        jLabel_user_pNumber.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user_pNumber.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user_pNumber.setText("Numero de celular");
        getContentPane().add(jLabel_user_pNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jTextField_user_pNumber.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user_pNumber.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user_pNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user_pNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_pNumberActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user_pNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 180, 20));

        jTextField_user_name.setBackground(new java.awt.Color(190, 221, 255));
        jTextField_user_name.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextField_user_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jTextField_user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 180, 20));

        jLabel_user_name.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel_user_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user_name.setText("Nombre completo");
        getContentPane().add(jLabel_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jButton_salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton_salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/register (1).png"))); // NOI18N
        getContentPane().add(jLabel_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        FonReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagen_fondo_5.jpeg"))); // NOI18N
        getContentPane().add(FonReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton_registrar.setText("jButton1");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_userActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        // ---->
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jTextField_user_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_emailActionPerformed

    private void jTextField_user_pNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_pNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_pNumberActionPerformed

    private void jTextField_user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_nameActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed
    
    // En el botón de registrar, llamamos a este método
    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        registrarUsuario();
    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FonReg;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_password1;
    private javax.swing.JLabel jLabel_registrarse;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JLabel jLabel_user_email;
    private javax.swing.JLabel jLabel_user_logo;
    private javax.swing.JLabel jLabel_user_name;
    private javax.swing.JLabel jLabel_user_pNumber;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_user;
    private javax.swing.JTextField jTextField_user_email;
    private javax.swing.JTextField jTextField_user_name;
    private javax.swing.JTextField jTextField_user_pNumber;
    // End of variables declaration//GEN-END:variables
}
